services:

    Polidog\PayjpBundle\Payjp:
        class: Polidog\PayjpBundle\Payjp
        arguments:
            - '@Polidog\PayjpBundle\Proxy\ClassFinder'

    Polidog\PayjpBundle\Proxy\CallApi:
        class: Polidog\PayjpBundle\Proxy\CallApi
        arguments:
            - "%polidog.web_pay.secret_key%"
        public: false

    Polidog\PayjpBundle\Proxy\ClassFinder:
        class: Polidog\PayjpBundle\Proxy\ClassFinder
        autowire: true
        arguments:
            $apiProxy: '@Polidog\PayjpBundle\Proxy\FireEvent'
        public: false

    Polidog\PayjpBundle\Proxy\FireEvent:
        class: Polidog\PayjpBundle\Proxy\FireEvent
        arguments:
            $apiProxy: '@Polidog\PayjpBundle\Proxy\CallApi'
        autowire: true
        public: false

    Polidog\PayjpBundle\Proxy\CheckApiResourceClass:
        class: Polidog\PayjpBundle\Proxy\CheckApiResourceClass
        arguments:
            - "Payjp\\ApiResource"
