services:

    Polidog\PayjpBundle\Payjp:
        class: Polidog\PayjpBundle\Payjp
        arguments:
            - '@Polidog\PayjpBundle\ApiDecorator\ClassFinder'

    Polidog\PayjpBundle\ApiDecorator\CallApi:
        class: Polidog\PayjpBundle\ApiDecorator\CallApi
        arguments:
            - "%polidog.web_pay.secret_key%"
        public: false

    Polidog\PayjpBundle\ApiDecorator\ClassFinder:
        class: Polidog\PayjpBundle\ApiDecorator\ClassFinder
        autowire: true
        arguments:
            $api: '@Polidog\PayjpBundle\ApiDecorator\FireEvent'
        public: false

    Polidog\PayjpBundle\ApiDecorator\FireEvent:
        class: Polidog\PayjpBundle\ApiDecorator\FireEvent
        arguments:
            $api: '@Polidog\PayjpBundle\ApiDecorator\CallApi'
        autowire: true
        public: false

    Polidog\PayjpBundle\ApiDecorator\CheckApiResourceClass:
        class: Polidog\PayjpBundle\ApiDecorator\CheckApiResourceClass
        arguments:
            - "Payjp\\ApiResource"

    Polidog\PayjpBundle\EventDispatcher\WebhookSubscriber:
        class: Polidog\PayjpBundle\EventDispatcher\WebhookSubscriber
        autowire: true
        arguments:
            $path: '%polidog.web_pay.webhook.path%'
            $token: '%polidog.web_pay.webhook.token%'
