services:

    Polidog\PayjpBundle\Payjp:
        class: Polidog\PayjpBundle\Payjp
        arguments:
            - "@Polidog\PayjpBundle\Proxy\MethodProxy"

    Polidog\PayjpBundle\Proxy\ApiProxy:
        class: Polidog\PayjpBundle\Proxy\ApiProxy
        arguments:
            - "%polidog.web_pay.secret_key%"
        public: false

    Polidog\PayjpBundle\Proxy\MethodProxy:
        class: Polidog\PayjpBundle\Proxy\MethodProxy
        autowire: true
        arguments:
            $apiProxy: '@Polidog\PayjpBundle\Proxy\ApiProxy'
        public: false


    Polidog\PayjpBundle\Proxy\CheckApiResourceClass:
        class: Polidog\PayjpBundle\Proxy\CheckApiResourceClass
        arguments:
            - "Payjp\\ApiResource"
